<a href="https://colab.research.google.com/github/alx1056/SP500-Stock-Scrape/blob/main/S%26P500_Webscrape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import bs4 as bs
import requests
import pandas as pd
 
resp = requests.get('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')
soup = bs.BeautifulSoup(resp.text, 'lxml')
table = soup.find('table', {'class': 'wikitable sortable'})
if len(table.contents) == 0:
  print("No table found")
else:
  print("Table extracted correctly!")
  print(type(table))

Table extracted correctly!
<class 'bs4.element.Tag'>

In [3]:
tickers = []
industries = []
for row in table.findAll('tr')[1:]:
        ticker = row.findAll('td')[0].text
        #fourth element is the sector
        industry = row.findAll('td')[4].text
        
        tickers.append(ticker)
        industries.append(industry)

In [4]:
print(tickers)

['MMM\n', 'ABT\n', 'ABBV\n', 'ABMD\n', 'ACN\n', 'ATVI\n', 'ADBE\n', 'AMD\n', 'AAP\n', 'AES\n', 'AFL\n', 'A\n', 'APD\n', 'AKAM\n', 'ALK\n', 'ALB\n', 'ARE\n', 'ALXN\n', 'ALGN\n', 'ALLE\n', 'LNT\n', 'ALL\n', 'GOOGL\n', 'GOOG\n', 'MO\n', 'AMZN\n', 'AMCR\n', 'AEE\n', 'AAL\n', 'AEP\n', 'AXP\n', 'AIG\n', 'AMT\n', 'AWK\n', 'AMP\n', 'ABC\n', 'AME\n', 'AMGN\n', 'APH\n', 'ADI\n', 'ANSS\n', 'ANTM\n', 'AON\n', 'AOS\n', 'APA\n', 'AAPL\n', 'AMAT\n', 'APTV\n', 'ADM\n', 'ANET\n', 'AJG\n', 'AIZ\n', 'T\n', 'ATO\n', 'ADSK\n', 'ADP\n', 'AZO\n', 'AVB\n', 'AVY\n', 'BKR\n', 'BLL\n', 'BAC\n', 'BK\n', 'BAX\n', 'BDX\n', 'BRK.B\n', 'BBY\n', 'BIO\n', 'BIIB\n', 'BLK\n', 'BA\n', 'BKNG\n', 'BWA\n', 'BXP\n', 'BSX\n', 'BMY\n', 'AVGO\n', 'BR\n', 'BF.B\n', 'CHRW\n', 'COG\n', 'CDNS\n', 'CPB\n', 'COF\n', 'CAH\n', 'KMX\n', 'CCL\n', 'CARR\n', 'CTLT\n', 'CAT\n', 'CBOE\n', 'CBRE\n', 'CDW\n', 'CE\n', 'CNC\n', 'CNP\n', 'CERN\n', 'CF\n', 'SCHW\n', 'CHTR\n', 'CVX\n', 'CMG\n', 'CB\n', 'CHD\n', 'CI\n', 'CINF\n', 'CTAS\n', 'CSCO\n', 'C\n', 'CFG\n', 'CTXS\n', 'CLX\n', 'CME\n', 'CMS\n', 'KO\n', 'CTSH\n', 'CL\n', 'CMCSA\n', 'CMA\n', 'CAG\n', 'COP\n', 'ED\n', 'STZ\n', 'COO\n', 'CPRT\n', 'GLW\n', 'CTVA\n', 'COST\n', 'CCI\n', 'CSX\n', 'CMI\n', 'CVS\n', 'DHI\n', 'DHR\n', 'DRI\n', 'DVA\n', 'DE\n', 'DAL\n', 'XRAY\n', 'DVN\n', 'DXCM\n', 'FANG\n', 'DLR\n', 'DFS\n', 'DISCA\n', 'DISCK\n', 'DISH\n', 'DG\n', 'DLTR\n', 'D\n', 'DPZ\n', 'DOV\n', 'DOW\n', 'DTE\n', 'DUK\n', 'DRE\n', 'DD\n', 'DXC\n', 'EMN\n', 'ETN\n', 'EBAY\n', 'ECL\n', 'EIX\n', 'EW\n', 'EA\n', 'EMR\n', 'ENPH\n', 'ETR\n', 'EOG\n', 'EFX\n', 'EQIX\n', 'EQR\n', 'ESS\n', 'EL\n', 'ETSY\n', 'EVRG\n', 'ES\n', 'RE\n', 'EXC\n', 'EXPE\n', 'EXPD\n', 'EXR\n', 'XOM\n', 'FFIV\n', 'FB\n', 'FAST\n', 'FRT\n', 'FDX\n', 'FIS\n', 'FITB\n', 'FE\n', 'FRC\n', 'FISV\n', 'FLT\n', 'FLIR\n', 'FLS\n', 'FMC\n', 'F\n', 'FTNT\n', 'FTV\n', 'FBHS\n', 'FOXA\n', 'FOX\n', 'BEN\n', 'FCX\n', 'GPS\n', 'GRMN\n', 'IT\n', 'GD\n', 'GE\n', 'GIS\n', 'GM\n', 'GPC\n', 'GILD\n', 'GL\n', 'GPN\n', 'GS\n', 'GWW\n', 'HAL\n', 'HBI\n', 'HIG\n', 'HAS\n', 'HCA\n', 'PEAK\n', 'HSIC\n', 'HSY\n', 'HES\n', 'HPE\n', 'HLT\n', 'HFC\n', 'HOLX\n', 'HD\n', 'HON\n', 'HRL\n', 'HST\n', 'HWM\n', 'HPQ\n', 'HUM\n', 'HBAN\n', 'HII\n', 'IEX\n', 'IDXX\n', 'INFO\n', 'ITW\n', 'ILMN\n', 'INCY\n', 'IR\n', 'INTC\n', 'ICE\n', 'IBM\n', 'IP\n', 'IPG\n', 'IFF\n', 'INTU\n', 'ISRG\n', 'IVZ\n', 'IPGP\n', 'IQV\n', 'IRM\n', 'JKHY\n', 'J\n', 'JBHT\n', 'SJM\n', 'JNJ\n', 'JCI\n', 'JPM\n', 'JNPR\n', 'KSU\n', 'K\n', 'KEY\n', 'KEYS\n', 'KMB\n', 'KIM\n', 'KMI\n', 'KLAC\n', 'KHC\n', 'KR\n', 'LB\n', 'LHX\n', 'LH\n', 'LRCX\n', 'LW\n', 'LVS\n', 'LEG\n', 'LDOS\n', 'LEN\n', 'LLY\n', 'LNC\n', 'LIN\n', 'LYV\n', 'LKQ\n', 'LMT\n', 'L\n', 'LOW\n', 'LUMN\n', 'LYB\n', 'MTB\n', 'MRO\n', 'MPC\n', 'MKTX\n', 'MAR\n', 'MMC\n', 'MLM\n', 'MAS\n', 'MA\n', 'MKC\n', 'MXIM\n', 'MCD\n', 'MCK\n', 'MDT\n', 'MRK\n', 'MET\n', 'MTD\n', 'MGM\n', 'MCHP\n', 'MU\n', 'MSFT\n', 'MAA\n', 'MHK\n', 'TAP\n', 'MDLZ\n', 'MNST\n', 'MCO\n', 'MS\n', 'MOS\n', 'MSI\n', 'MSCI\n', 'NDAQ\n', 'NTAP\n', 'NFLX\n', 'NWL\n', 'NEM\n', 'NWSA\n', 'NWS\n', 'NEE\n', 'NLSN\n', 'NKE\n', 'NI\n', 'NSC\n', 'NTRS\n', 'NOC\n', 'NLOK\n', 'NCLH\n', 'NOV\n', 'NRG\n', 'NUE\n', 'NVDA\n', 'NVR\n', 'ORLY\n', 'OXY\n', 'ODFL\n', 'OMC\n', 'OKE\n', 'ORCL\n', 'OTIS\n', 'PCAR\n', 'PKG\n', 'PH\n', 'PAYX\n', 'PAYC\n', 'PYPL\n', 'PNR\n', 'PBCT\n', 'PEP\n', 'PKI\n', 'PRGO\n', 'PFE\n', 'PM\n', 'PSX\n', 'PNW\n', 'PXD\n', 'PNC\n', 'POOL\n', 'PPG\n', 'PPL\n', 'PFG\n', 'PG\n', 'PGR\n', 'PLD\n', 'PRU\n', 'PEG\n', 'PSA\n', 'PHM\n', 'PVH\n', 'QRVO\n', 'PWR\n', 'QCOM\n', 'DGX\n', 'RL\n', 'RJF\n', 'RTX\n', 'O\n', 'REG\n', 'REGN\n', 'RF\n', 'RSG\n', 'RMD\n', 'RHI\n', 'ROK\n', 'ROL\n', 'ROP\n', 'ROST\n', 'RCL\n', 'SPGI\n', 'CRM\n', 'SBAC\n', 'SLB\n', 'STX\n', 'SEE\n', 'SRE\n', 'NOW\n', 'SHW\n', 'SPG\n', 'SWKS\n', 'SLG\n', 'SNA\n', 'SO\n', 'LUV\n', 'SWK\n', 'SBUX\n', 'STT\n', 'STE\n', 'SYK\n', 'SIVB\n', 'SYF\n', 'SNPS\n', 'SYY\n', 'TMUS\n', 'TROW\n', 'TTWO\n', 'TPR\n', 'TGT\n', 'TEL\n', 'FTI\n', 'TDY\n', 'TFX\n', 'TER\n', 'TSLA\n', 'TXN\n', 'TXT\n', 'TMO\n', 'TJX\n', 'TSCO\n', 'TT\n', 'TDG\n', 'TRV\n', 'TRMB\n', 'TFC\n', 'TWTR\n', 'TYL\n', 'TSN\n', 'UDR\n', 'ULTA\n', 'USB\n', 'UAA\n', 'UA\n', 'UNP\n', 'UAL\n', 'UNH\n', 'UPS\n', 'URI\n', 'UHS\n', 'UNM\n', 'VLO\n', 'VAR\n', 'VTR\n', 'VRSN\n', 'VRSK\n', 'VZ\n', 'VRTX\n', 'VFC\n', 'VIAC\n', 'VTRS\n', 'V\n', 'VNT\n', 'VNO\n', 'VMC\n', 'WRB\n', 'WAB\n', 'WMT\n', 'WBA\n', 'DIS\n', 'WM\n', 'WAT\n', 'WEC\n', 'WFC\n', 'WELL\n', 'WST\n', 'WDC\n', 'WU\n', 'WRK\n', 'WY\n', 'WHR\n', 'WMB\n', 'WLTW\n', 'WYNN\n', 'XEL\n', 'XRX\n', 'XLNX\n', 'XYL\n', 'YUM\n', 'ZBRA\n', 'ZBH\n', 'ZION\n', 'ZTS\n']

In [5]:
tickers = list(map(lambda s: s.strip(), tickers))
industries = list(map(lambda s: s.strip(), industries))

print(tickers)

['MMM', 'ABT', 'ABBV', 'ABMD', 'ACN', 'ATVI', 'ADBE', 'AMD', 'AAP', 'AES', 'AFL', 'A', 'APD', 'AKAM', 'ALK', 'ALB', 'ARE', 'ALXN', 'ALGN', 'ALLE', 'LNT', 'ALL', 'GOOGL', 'GOOG', 'MO', 'AMZN', 'AMCR', 'AEE', 'AAL', 'AEP', 'AXP', 'AIG', 'AMT', 'AWK', 'AMP', 'ABC', 'AME', 'AMGN', 'APH', 'ADI', 'ANSS', 'ANTM', 'AON', 'AOS', 'APA', 'AAPL', 'AMAT', 'APTV', 'ADM', 'ANET', 'AJG', 'AIZ', 'T', 'ATO', 'ADSK', 'ADP', 'AZO', 'AVB', 'AVY', 'BKR', 'BLL', 'BAC', 'BK', 'BAX', 'BDX', 'BRK.B', 'BBY', 'BIO', 'BIIB', 'BLK', 'BA', 'BKNG', 'BWA', 'BXP', 'BSX', 'BMY', 'AVGO', 'BR', 'BF.B', 'CHRW', 'COG', 'CDNS', 'CPB', 'COF', 'CAH', 'KMX', 'CCL', 'CARR', 'CTLT', 'CAT', 'CBOE', 'CBRE', 'CDW', 'CE', 'CNC', 'CNP', 'CERN', 'CF', 'SCHW', 'CHTR', 'CVX', 'CMG', 'CB', 'CHD', 'CI', 'CINF', 'CTAS', 'CSCO', 'C', 'CFG', 'CTXS', 'CLX', 'CME', 'CMS', 'KO', 'CTSH', 'CL', 'CMCSA', 'CMA', 'CAG', 'COP', 'ED', 'STZ', 'COO', 'CPRT', 'GLW', 'CTVA', 'COST', 'CCI', 'CSX', 'CMI', 'CVS', 'DHI', 'DHR', 'DRI', 'DVA', 'DE', 'DAL', 'XRAY', 'DVN', 'DXCM', 'FANG', 'DLR', 'DFS', 'DISCA', 'DISCK', 'DISH', 'DG', 'DLTR', 'D', 'DPZ', 'DOV', 'DOW', 'DTE', 'DUK', 'DRE', 'DD', 'DXC', 'EMN', 'ETN', 'EBAY', 'ECL', 'EIX', 'EW', 'EA', 'EMR', 'ENPH', 'ETR', 'EOG', 'EFX', 'EQIX', 'EQR', 'ESS', 'EL', 'ETSY', 'EVRG', 'ES', 'RE', 'EXC', 'EXPE', 'EXPD', 'EXR', 'XOM', 'FFIV', 'FB', 'FAST', 'FRT', 'FDX', 'FIS', 'FITB', 'FE', 'FRC', 'FISV', 'FLT', 'FLIR', 'FLS', 'FMC', 'F', 'FTNT', 'FTV', 'FBHS', 'FOXA', 'FOX', 'BEN', 'FCX', 'GPS', 'GRMN', 'IT', 'GD', 'GE', 'GIS', 'GM', 'GPC', 'GILD', 'GL', 'GPN', 'GS', 'GWW', 'HAL', 'HBI', 'HIG', 'HAS', 'HCA', 'PEAK', 'HSIC', 'HSY', 'HES', 'HPE', 'HLT', 'HFC', 'HOLX', 'HD', 'HON', 'HRL', 'HST', 'HWM', 'HPQ', 'HUM', 'HBAN', 'HII', 'IEX', 'IDXX', 'INFO', 'ITW', 'ILMN', 'INCY', 'IR', 'INTC', 'ICE', 'IBM', 'IP', 'IPG', 'IFF', 'INTU', 'ISRG', 'IVZ', 'IPGP', 'IQV', 'IRM', 'JKHY', 'J', 'JBHT', 'SJM', 'JNJ', 'JCI', 'JPM', 'JNPR', 'KSU', 'K', 'KEY', 'KEYS', 'KMB', 'KIM', 'KMI', 'KLAC', 'KHC', 'KR', 'LB', 'LHX', 'LH', 'LRCX', 'LW', 'LVS', 'LEG', 'LDOS', 'LEN', 'LLY', 'LNC', 'LIN', 'LYV', 'LKQ', 'LMT', 'L', 'LOW', 'LUMN', 'LYB', 'MTB', 'MRO', 'MPC', 'MKTX', 'MAR', 'MMC', 'MLM', 'MAS', 'MA', 'MKC', 'MXIM', 'MCD', 'MCK', 'MDT', 'MRK', 'MET', 'MTD', 'MGM', 'MCHP', 'MU', 'MSFT', 'MAA', 'MHK', 'TAP', 'MDLZ', 'MNST', 'MCO', 'MS', 'MOS', 'MSI', 'MSCI', 'NDAQ', 'NTAP', 'NFLX', 'NWL', 'NEM', 'NWSA', 'NWS', 'NEE', 'NLSN', 'NKE', 'NI', 'NSC', 'NTRS', 'NOC', 'NLOK', 'NCLH', 'NOV', 'NRG', 'NUE', 'NVDA', 'NVR', 'ORLY', 'OXY', 'ODFL', 'OMC', 'OKE', 'ORCL', 'OTIS', 'PCAR', 'PKG', 'PH', 'PAYX', 'PAYC', 'PYPL', 'PNR', 'PBCT', 'PEP', 'PKI', 'PRGO', 'PFE', 'PM', 'PSX', 'PNW', 'PXD', 'PNC', 'POOL', 'PPG', 'PPL', 'PFG', 'PG', 'PGR', 'PLD', 'PRU', 'PEG', 'PSA', 'PHM', 'PVH', 'QRVO', 'PWR', 'QCOM', 'DGX', 'RL', 'RJF', 'RTX', 'O', 'REG', 'REGN', 'RF', 'RSG', 'RMD', 'RHI', 'ROK', 'ROL', 'ROP', 'ROST', 'RCL', 'SPGI', 'CRM', 'SBAC', 'SLB', 'STX', 'SEE', 'SRE', 'NOW', 'SHW', 'SPG', 'SWKS', 'SLG', 'SNA', 'SO', 'LUV', 'SWK', 'SBUX', 'STT', 'STE', 'SYK', 'SIVB', 'SYF', 'SNPS', 'SYY', 'TMUS', 'TROW', 'TTWO', 'TPR', 'TGT', 'TEL', 'FTI', 'TDY', 'TFX', 'TER', 'TSLA', 'TXN', 'TXT', 'TMO', 'TJX', 'TSCO', 'TT', 'TDG', 'TRV', 'TRMB', 'TFC', 'TWTR', 'TYL', 'TSN', 'UDR', 'ULTA', 'USB', 'UAA', 'UA', 'UNP', 'UAL', 'UNH', 'UPS', 'URI', 'UHS', 'UNM', 'VLO', 'VAR', 'VTR', 'VRSN', 'VRSK', 'VZ', 'VRTX', 'VFC', 'VIAC', 'VTRS', 'V', 'VNT', 'VNO', 'VMC', 'WRB', 'WAB', 'WMT', 'WBA', 'DIS', 'WM', 'WAT', 'WEC', 'WFC', 'WELL', 'WST', 'WDC', 'WU', 'WRK', 'WY', 'WHR', 'WMB', 'WLTW', 'WYNN', 'XEL', 'XRX', 'XLNX', 'XYL', 'YUM', 'ZBRA', 'ZBH', 'ZION', 'ZTS']

In [6]:
tickerdf = pd.DataFrame(tickers,columns=['ticker'])
sectordf = pd.DataFrame(industries,columns=['industry'])

In [7]:
tickerandsector =pd.merge(tickerdf, sectordf, on = tickerdf.index, how = "outer")
tickerandsector = tickerandsector.drop('key_0', axis=1)

In [8]:
tickerandsector

    ticker                            industry
0      MMM            Industrial Conglomerates
1      ABT               Health Care Equipment
2     ABBV                     Pharmaceuticals
3     ABMD               Health Care Equipment
4      ACN      IT Consulting & Other Services
..     ...                                 ...
500    YUM                         Restaurants
501   ZBRA  Electronic Equipment & Instruments
502    ZBH               Health Care Equipment
503   ZION                      Regional Banks
504    ZTS                     Pharmaceuticals

[505 rows x 2 columns]

In [9]:
ind = pd.DataFrame(tickerandsector['industry'].unique(), columns=['Industry Sector'])
print(ind)

                         Industry Sector
0               Industrial Conglomerates
1                  Health Care Equipment
2                        Pharmaceuticals
3         IT Consulting & Other Services
4         Interactive Home Entertainment
..                                   ...
119                    Food Distributors
120  Wireless Telecommunication Services
121     Trading Companies & Distributors
122                          Drug Retail
123                 Household Appliances

[124 rows x 1 columns]

In [10]:
filtersector = tickerandsector.loc[tickerandsector['industry'] == 'Industry Sector']

listoftickers =  filtersector['ticker'].tolist()
print(listoftickers)

[]

In [21]:
#mirror tickerdf Datafram to Stock Symbol
stock_symbol = tickerdf
tickerdf

    ticker
0      MMM
1      ABT
2     ABBV
3     ABMD
4      ACN
..     ...
500    YUM
501   ZBRA
502    ZBH
503   ZION
504    ZTS

[505 rows x 1 columns]

In [20]:
#test run to show only first 50 stocks
price_close = []
value = []

for j in range(len(stock_symbol[1:50])):
    link = 'https://finance.yahoo.com/quote/'+stock_symbol["ticker"].iloc[j]+'?p='+stock_symbol["ticker"].iloc[j]
    #webbrowser.open(link)
    page = requests.get(link)
    html_soup = bs.BeautifulSoup(page.content, 'html.parser')
    price_close.append(html_soup.find('span', attrs = {'class' : 'Trsdu(0.3s) Fw(b) Fz(36px) Mb(-4px) D(ib)'}).text)
    page = requests.get(link)
    html_soup = bs.BeautifulSoup(page.content, 'html.parser')
    #price_close.append(html_soup.find('span', attrs = {'class' : 'Trsdu(0.3s) Fw(b) Fz(36px) Mb(-4px) D(ib)'}).text)
    x = html_soup.find('div', attrs = {'class' : 'Fw(b) Fl(end)--m Fz(s) C($primaryColor'}).get_text()
    if 'Overvalued' in x:
        value.append('Overvalued')
    elif 'Undervalued' in x:
        value.append('Undervalued')
    elif 'Nuetral' in x:
        value.append('Nuetral')
    elif 'Near Fair Value' in x:
        value.append('Near Fair Value')
    else:
        value.append('N/A')



price_close = pd.DataFrame(price_close, columns=['Closing Price'])
value = pd.DataFrame(value, columns=['Value'])

print(value)
print("\n")
print(price_close)
print("\n")
print(tickerdf.iloc[range(len(stock_symbol[1:50]))])

              Value
0        Overvalued
1        Overvalued
2        Overvalued
3   Near Fair Value
4        Overvalued
5        Overvalued
6   Near Fair Value
7        Overvalued
8   Near Fair Value
9        Overvalued
10  Near Fair Value
11       Overvalued
12       Overvalued
13  Near Fair Value
14       Overvalued
15  Near Fair Value
16  Near Fair Value
17      Undervalued
18  Near Fair Value
19       Overvalued
20       Overvalued
21      Undervalued
22      Undervalued
23      Undervalued
24       Overvalued
25  Near Fair Value
26       Overvalued
27       Overvalued
28      Undervalued
29       Overvalued
30      Undervalued
31  Near Fair Value
32  Near Fair Value
33       Overvalued
34  Near Fair Value
35  Near Fair Value
36       Overvalued
37  Near Fair Value
38       Overvalued
39       Overvalued
40       Overvalued
41  Near Fair Value
42       Overvalued
43       Overvalued
44       Overvalued
45       Overvalued
46       Overvalued
47       Overvalued
48       Overvalued


   Closing Price
0         186.01
1         122.25
2         104.65
3         376.86
4         250.42
5          90.93
6         464.26
7          88.36
8         151.48
9          24.08
10         46.33
11        121.56
12        276.17
13        114.85
14         51.00
15        164.73
16        168.50
17        157.86
18        537.15
19        113.77
20         49.51
21        110.95
22      1,851.04
23      1,862.07
24         42.88
25      3,267.64
26         11.23
27         75.74
28         18.21
29         81.96
30        118.22
31         38.49
32        230.32
33        160.75
34        201.33
35        109.31
36        114.71
37        257.72
38        126.01
39        149.46
40        363.87
41        302.90
42        208.36
43         59.46
44         14.80
45        139.27
46        101.21
47        130.73
48         50.16


   ticker
0     MMM
1     ABT
2    ABBV
3    ABMD
4     ACN
5    ATVI
6    ADBE
7     AMD
8     AAP
9     AES
10    AFL
11      A
12    APD
13   AKAM
14    ALK
15    ALB
16    ARE
17   ALXN
18   ALGN
19   ALLE
20    LNT
21    ALL
22  GOOGL
23   GOOG
24     MO
25   AMZN
26   AMCR
27    AEE
28    AAL
29    AEP
30    AXP
31    AIG
32    AMT
33    AWK
34    AMP
35    ABC
36    AME
37   AMGN
38    APH
39    ADI
40   ANSS
41   ANTM
42    AON
43    AOS
44    APA
45   AAPL
46   AMAT
47   APTV
48    ADM

In [14]:
df = pd.merge(price_close, tickerdf, left_index=True, right_index=True)
df

   Closing Price ticker
0         185.71    MMM
1         122.54    ABT
2         104.67   ABBV
3         374.00   ABMD
4         250.16    ACN
5          90.75   ATVI
6         464.59   ADBE
7          88.35    AMD
8         150.99    AAP
9          23.97    AES
10         46.29    AFL
11        121.27      A
12        275.55    APD
13        115.18   AKAM
14         50.97    ALK
15        165.23    ALB
16        168.32    ARE
17        157.64   ALXN
18        534.58   ALGN
19        113.88   ALLE
20         49.38    LNT
21        110.68    ALL
22      1,848.69  GOOGL
23      1,858.45   GOOG
24         42.76     MO
25      3,262.74   AMZN
26         11.24   AMCR
27         75.75    AEE
28         18.41    AAL
29         81.94    AEP
30        118.02    AXP
31         38.50    AIG
32        229.89    AMT
33        160.13    AWK
34        200.95    AMP
35        109.22    ABC
36        114.65    AME
37        256.67   AMGN
38        125.97    APH
39        149.41    ADI
40        363.38   ANSS
41        302.54   ANTM
42        207.95    AON
43         59.78    AOS
44         14.85    APA
45        139.03   AAPL
46        101.00   AMAT
47        130.62   APTV
48         50.19    ADM

In [22]:
df_other =  pd.merge(df , value, left_index=True, right_index=True, sort = True)
df_other

   Closing Price ticker            Value
0         185.71    MMM       Overvalued
1         122.54    ABT       Overvalued
2         104.67   ABBV       Overvalued
3         374.00   ABMD  Near Fair Value
4         250.16    ACN       Overvalued
5          90.75   ATVI       Overvalued
6         464.59   ADBE  Near Fair Value
7          88.35    AMD       Overvalued
8         150.99    AAP  Near Fair Value
9          23.97    AES       Overvalued
10         46.29    AFL  Near Fair Value
11        121.27      A       Overvalued
12        275.55    APD       Overvalued
13        115.18   AKAM  Near Fair Value
14         50.97    ALK       Overvalued
15        165.23    ALB  Near Fair Value
16        168.32    ARE  Near Fair Value
17        157.64   ALXN      Undervalued
18        534.58   ALGN  Near Fair Value
19        113.88   ALLE       Overvalued
20         49.38    LNT       Overvalued
21        110.68    ALL      Undervalued
22      1,848.69  GOOGL      Undervalued
23      1,858.45   GOOG      Undervalued
24         42.76     MO       Overvalued
25      3,262.74   AMZN  Near Fair Value
26         11.24   AMCR       Overvalued
27         75.75    AEE       Overvalued
28         18.41    AAL      Undervalued
29         81.94    AEP       Overvalued
30        118.02    AXP      Undervalued
31         38.50    AIG  Near Fair Value
32        229.89    AMT  Near Fair Value
33        160.13    AWK       Overvalued
34        200.95    AMP  Near Fair Value
35        109.22    ABC  Near Fair Value
36        114.65    AME       Overvalued
37        256.67   AMGN  Near Fair Value
38        125.97    APH       Overvalued
39        149.41    ADI       Overvalued
40        363.38   ANSS       Overvalued
41        302.54   ANTM  Near Fair Value
42        207.95    AON       Overvalued
43         59.78    AOS       Overvalued
44         14.85    APA       Overvalued
45        139.03   AAPL       Overvalued
46        101.00   AMAT       Overvalued
47        130.62   APTV       Overvalued
48         50.19    ADM       Overvalued

In [23]:
df_final = pd.merge(ind , df_other, left_index=True, right_index=True, sort = True)
df_final.sort_values(by=['Industry Sector'], ascending=True)

                                 Industry Sector  ...            Value
38                         Agricultural Products  ...       Overvalued
12                                      Airlines  ...       Overvalued
5                           Application Software  ...       Overvalued
27              Asset Management & Custody Banks  ...       Overvalued
37                        Auto Parts & Equipment  ...  Near Fair Value
7                              Automotive Retail  ...       Overvalued
30                                 Biotechnology  ...      Undervalued
16                             Building Products  ...  Near Fair Value
39                      Communications Equipment  ...       Overvalued
24                              Consumer Finance  ...       Overvalued
43         Data Processing & Outsourced Services  ...       Overvalued
48                             Diversified Banks  ...       Overvalued
17                            Electric Utilities  ...      Undervalued
29             Electrical Components & Equipment  ...       Overvalued
31                         Electronic Components  ...  Near Fair Value
42                                 Gas Utilities  ...       Overvalued
28                      Health Care Distributors  ...      Undervalued
1                          Health Care Equipment  ...       Overvalued
15                          Health Care Supplies  ...  Near Fair Value
3                 IT Consulting & Other Services  ...  Near Fair Value
8   Independent Power Producers & Energy Traders  ...  Near Fair Value
0                       Industrial Conglomerates  ...       Overvalued
10                              Industrial Gases  ...  Near Fair Value
33                             Insurance Brokers  ...       Overvalued
41         Integrated Telecommunication Services  ...  Near Fair Value
4                 Interactive Home Entertainment  ...       Overvalued
19                  Interactive Media & Services  ...       Overvalued
21            Internet & Direct Marketing Retail  ...      Undervalued
11            Internet Services & Infrastructure  ...       Overvalued
9                        Life & Health Insurance  ...       Overvalued
32                           Managed Health Care  ...  Near Fair Value
47                      Metal & Glass Containers  ...       Overvalued
23                               Multi-Utilities  ...      Undervalued
40                          Multi-line Insurance  ...       Overvalued
14                                  Office REITs  ...       Overvalued
46                Oil & Gas Equipment & Services  ...       Overvalued
34            Oil & Gas Exploration & Production  ...  Near Fair Value
22                               Paper Packaging  ...      Undervalued
2                                Pharmaceuticals  ...       Overvalued
18                 Property & Casualty Insurance  ...  Near Fair Value
45                             Residential REITs  ...       Overvalued
36                       Semiconductor Equipment  ...       Overvalued
6                                 Semiconductors  ...  Near Fair Value
25                             Specialized REITs  ...  Near Fair Value
13                           Specialty Chemicals  ...  Near Fair Value
44                              Specialty Stores  ...       Overvalued
35    Technology Hardware, Storage & Peripherals  ...  Near Fair Value
20                                       Tobacco  ...       Overvalued
26                               Water Utilities  ...       Overvalued

[49 rows x 4 columns]

In [41]:
import datetime
x = datetime.datetime.now()
name = x.strftime("%a_%d_%y_") + "S&P500"

#saves onto excel file
df_final.to_excel("Portfolio.xlsx", sheet_name=name, index=False)
print("Excel file created Succesfully!")

Excel file created Succesfully!